lanugage: node_js

services: 
  - docker

before_install:
  - docker pull lrilling/podcast-whisperer
  - docker run -v /app:/app lrilling/podcast-whisperer
  - docker ps


install:
  - npm install

script: 
  - gulp build
  - npm test