name: "Github Action Testing"
on: [push]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/lrilling/podcast-whisperer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace}}:/app
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "See directory"
        run: ls -l app
      - name: "Install dependencies"
        run: npm install
        working-directory: ./app
      - name: "Build app"
        run: gulp build
        working-directory: ./app
      - name: "Start testing"
        run: npm run test
        working-directory: ./app
  
  test-without-container:
    runs-on: ubuntu-latest
    # container: 
    #   image: ghcr.io/lrilling/podcast-whisperer:latest
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@v1
    - name: "Install Node"
      uses: actions/setup-node@v1
      with:
        node-version: 18.12.1
    - name: "Install Mocha"
      run: npm install -g mocha
    - name: "Install dependencies"
      run: npm install
      working-directory: ./app
    - name: "Build project"
      run: gulp build
      working-directory: ./app
    - name: "Run tests"
      run: npm test
      working-directory: ./app
      