name: "Github Action Testing"
on: [push]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/lrilling/podcast-whisperer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: "See directory"
        uses: lrilling/podcast-whisperer
      # - name: "Checkout"
      #   uses: actions/checkout@v1
      # - name: "Build app"
      #   run: gulp build
      #   working-directory: ./app
      # - name: "Start testing"
      #   run: npm run test
      #   working-directory: ./app